# Generated by Django 5.0.2 on 2024-11-06 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dueentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailerprofile',
            name='existing_bank_account',
        ),
        migrations.AddField(
            model_name='retailerprofile',
            name='employee_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='retailerprofile',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='retailerprofile',
            name='annual_turnover',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='retailerprofile',
            name='business_type',
            field=models.CharField(default='retail_store', max_length=50),
        ),
        migrations.AlterField(
            model_name='retailerprofile',
            name='pan_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='retailerprofile',
            name='shop_ownership',
            field=models.CharField(choices=[('owned', 'Owned'), ('rented', 'Rented')], default='rented', max_length=20),
        ),
        migrations.AlterField(
            model_name='retailerprofile',
            name='years_in_business',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='business_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gst_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('retailer', 'Retailer'), ('fintech', 'Fintech')], max_length=10),
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_branch', models.CharField(max_length=100)),
                ('retailer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.retailerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CreditAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.retailerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('gst_certificate', 'GST Certificate'), ('bank_statement', 'Bank Statement'), ('financial_statement', 'Financial Statement'), ('shop_license', 'Shop License'), ('ownership_docs', 'Ownership Documents')], max_length=50)),
                ('file', models.FileField(upload_to='retailer_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.retailerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExistingLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_provider', models.CharField(max_length=100)),
                ('monthly_emi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.retailerprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='CreditLimit',
        ),
    ]
