# Generated by Django 5.0.2 on 2024-11-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bankdetails_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerprofile',
            name='available_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='retailerprofile',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
